functionsDirectory = "/Users/matrix/code/dxp/platform/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "/Users/matrix/code/dxp/platform"
publishOrigin = "config"
functions = "/Users/matrix/code/dxp/platform/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
included_files = ["data/posts.json"]
node_bundler = "esbuild"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/admin"
to = "/admin.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]